/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appstage;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Badr
 */
public class Add extends javax.swing.JFrame {

	Connecter conn = new Connecter();
	Statement stm;
	ResultSet Rs;
	DefaultTableModel model = new DefaultTableModel();

	/**
	 * Creates new form Add
	 */
	public Add() {
		initComponents();
		// jPanel2.setOpaque(false);
		jPanel_Add.setVisible(true);
		jPanel_Add.setOpaque(false);
		// jPanel_Add.setBackground(new Color(0,0,0,25));
		jPanel_Delete.setVisible(false);
		jPanel_Delete.setOpaque(false);
		jPanel_Search.setVisible(false);
		jPanel_Search.setOpaque(false);
		jPanel_Edit.setOpaque(false);
		jPanel_Edit.setVisible(false);

		model.addColumn("N_Clt");
		model.addColumn("N_Immat");
		model.addColumn("Nom_Clt");
		model.addColumn("Prenom_Clt");
		model.addColumn("Tele");
		model.addColumn("N_RDV");
		model.addColumn("Date_In");
		model.addColumn("Time_In");
		model.addColumn("Date_Out");
		model.addColumn("Time_Out");
		model.addColumn("Reparation");
		model.addColumn("Marque");
		model.addColumn("Model");
		model.addColumn("Num_Chas");

		try {
			stm = conn.obtenirconnexion().createStatement();
			ResultSet Rs = stm.executeQuery("Select * from Client");
			while (Rs.next()) {
				model.addRow(new Object[] { Rs.getString("N_Clt"), Rs.getString("N_Immat"), Rs.getString("Nom_Clt"),
						Rs.getString("Prenom_Clt"), Rs.getString("Tele"), Rs.getString("N_RV"), Rs.getString("Date_In"),
						Rs.getString("Heur_In"), Rs.getString("Date_Out"), Rs.getString("Heur_Out"),
						Rs.getString("Reparation"), Rs.getString("Marque"), Rs.getString("Model"),
						Rs.getString("Num_Chas") });
			}
		} catch (Exception e) {
			System.err.println(e);
		}

		tble.setModel(model);
		tble1.setModel(model);

	}

	private void deplace(int i) {
		try {
			// Add A = new Add();
			// Txt_PreClt1.setText(model.getValueAt(i,3).toString());
			Txt_TeleClt1.setText(model.getValueAt(i, 4).toString());
			Txt_NRDV.setText(model.getValueAt(i, 5).toString());
			DateC_In1.setDateFormatString(model.getValueAt(i, 6).toString());
			// A.getTxt_TeleClt().setText(model.getValueAt(i,8).toString());/*time
			// _in*/
			DateC_Out1.setDateFormatString(model.getValueAt(i, 7).toString());
			// A.getTxt_TeleClt().setText(model.getValueAt(i,8).toString());/*time
			// _out*/
			Combo_Rep1.setSelectedItem(model.getValueAt(i, 10).toString());
			Txt_Marque1.setText(model.getValueAt(i, 11).toString());
			Txt_Model.setText(model.getValueAt(i, 12).toString());
			Txt_NChas1.setText(model.getValueAt(i, 13).toString());
		} catch (Exception e) {
			System.err.println(e);
			JOptionPane.showMessageDialog(null, "erreur de deplacement" + e.getLocalizedMessage());
		}
	}

	private void Refresh() {
		try {
			model.setRowCount(0);
			stm = conn.obtenirconnexion().createStatement();
			ResultSet Rs = stm.executeQuery("Select * from Client");
			while (Rs.next()) {
				model.addRow(new Object[] { Rs.getString("N_Clt"), Rs.getString("N_Immat"), Rs.getString("Nom_Clt"),
						Rs.getString("Prenom_Clt"), Rs.getString("Tele"), Rs.getString("N_RV"), Rs.getString("Date_In"),
						Rs.getString("Heur_In"), Rs.getString("Date_Out"), Rs.getString("Heur_Out"),
						Rs.getString("Reparation"), Rs.getString("Marque"), Rs.getString("Model"),
						Rs.getString("Num_Chas") });
			}
		} catch (Exception e) {
			System.err.println(e);
		}

		tble.setModel(model);
		tble1.setModel(model);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton4 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel_Edit = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		Txt_NRDV1 = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		DateC_Out1 = new com.toedter.calendar.JDateChooser();
		DateC_In1 = new com.toedter.calendar.JDateChooser();
		Combo_Rep1 = new javax.swing.JComboBox();
		jPanel6 = new javax.swing.JPanel();
		jLabel22 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabel24 = new javax.swing.JLabel();
		jLabel25 = new javax.swing.JLabel();
		Txt_NChas1 = new javax.swing.JTextField();
		Txt_Model1 = new javax.swing.JTextField();
		Txt_Marque1 = new javax.swing.JTextField();
		Txt_Immat1 = new javax.swing.JTextField();
		Btn_AddToData1 = new javax.swing.JButton();
		jPanel7 = new javax.swing.JPanel();
		Txt_NumClt1 = new javax.swing.JTextField();
		jLabel26 = new javax.swing.JLabel();
		Txt_NomClt1 = new javax.swing.JTextField();
		jLabel27 = new javax.swing.JLabel();
		Txt_PreClt1 = new javax.swing.JTextField();
		jLabel28 = new javax.swing.JLabel();
		Txt_TeleClt1 = new javax.swing.JTextField();
		jLabel29 = new javax.swing.JLabel();
		jPanel_Search = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		Combo_Search = new javax.swing.JComboBox();
		Txt_Search = new javax.swing.JTextField();
		jButton_Find = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		tble1 = new javax.swing.JTable();
		jButton_FindDel = new javax.swing.JButton();
		jButton_FindEdit = new javax.swing.JButton();
		jPanel_Delete = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tble = new javax.swing.JTable();
		jButton_Delete = new javax.swing.JButton();
		jPanel_Add = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		Txt_NRDV = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		DateC_Out = new com.toedter.calendar.JDateChooser();
		DateC_In = new com.toedter.calendar.JDateChooser();
		Combo_Rep = new javax.swing.JComboBox();
		jPanel1 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		Txt_NChas = new javax.swing.JTextField();
		Txt_Model = new javax.swing.JTextField();
		Txt_Marque = new javax.swing.JTextField();
		Txt_Immat = new javax.swing.JTextField();
		Btn_AddToData = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		Txt_NumClt = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		Txt_NomClt = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		Txt_PreClt = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		Txt_TeleClt = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(810, 610));
		getContentPane().setLayout(null);

		jButton4.setText("Add");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton4);
		jButton4.setBounds(40, 200, 190, 30);

		jButton1.setText("Edit");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton1);
		jButton1.setBounds(40, 240, 190, 30);

		jButton2.setText("Delete");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton2);
		jButton2.setBounds(40, 280, 190, 30);

		jButton5.setText("Search");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton5);
		jButton5.setBounds(40, 320, 190, 30);

		jButton3.setText("Reparation Situation");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton3);
		jButton3.setBounds(40, 410, 190, 30);

		jPanel_Edit.setPreferredSize(new java.awt.Dimension(1500, 1500));
		jPanel_Edit.setLayout(null);

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Réparation",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
		jPanel4.setLayout(null);

		Txt_NRDV1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_NRDV1ActionPerformed(evt);
			}
		});
		jPanel4.add(Txt_NRDV1);
		Txt_NRDV1.setBounds(100, 20, 130, 30);

		jLabel18.setText("Num_RDV");
		jPanel4.add(jLabel18);
		jLabel18.setBounds(30, 30, 85, 23);

		jLabel19.setText("Date_In");
		jPanel4.add(jLabel19);
		jLabel19.setBounds(30, 70, 85, 23);

		jLabel20.setText("Reparation");
		jPanel4.add(jLabel20);
		jLabel20.setBounds(270, 30, 85, 23);

		jLabel21.setText("Date_Out");
		jPanel4.add(jLabel21);
		jLabel21.setBounds(270, 70, 85, 23);
		jPanel4.add(DateC_Out1);
		DateC_Out1.setBounds(350, 60, 130, 30);
		jPanel4.add(DateC_In1);
		DateC_In1.setBounds(100, 60, 130, 30);

		Combo_Rep1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rep 1", "Rep 2", "Rep 3", "Rep 4" }));
		jPanel4.add(Combo_Rep1);
		Combo_Rep1.setBounds(350, 20, 130, 30);

		jPanel_Edit.add(jPanel4);
		jPanel4.setBounds(10, 200, 510, 100);

		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Voiture",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
		jPanel6.setLayout(null);

		jLabel22.setText("Immatrcule");
		jPanel6.add(jLabel22);
		jLabel22.setBounds(10, 20, 85, 23);

		jLabel23.setText("Marque");
		jPanel6.add(jLabel23);
		jLabel23.setBounds(10, 60, 85, 23);

		jLabel24.setText("Model");
		jPanel6.add(jLabel24);
		jLabel24.setBounds(10, 100, 85, 23);

		jLabel25.setText("Num_Chas");
		jPanel6.add(jLabel25);
		jLabel25.setBounds(10, 140, 85, 23);
		jPanel6.add(Txt_NChas1);
		Txt_NChas1.setBounds(90, 130, 130, 30);
		jPanel6.add(Txt_Model1);
		Txt_Model1.setBounds(90, 90, 130, 30);
		jPanel6.add(Txt_Marque1);
		Txt_Marque1.setBounds(90, 50, 130, 30);

		Txt_Immat1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_Immat1ActionPerformed(evt);
			}
		});
		jPanel6.add(Txt_Immat1);
		Txt_Immat1.setBounds(90, 10, 130, 30);

		jPanel_Edit.add(jPanel6);
		jPanel6.setBounds(280, 10, 240, 170);

		Btn_AddToData1.setText("Modifier");
		Btn_AddToData1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Btn_AddToData1ActionPerformed(evt);
			}
		});
		jPanel_Edit.add(Btn_AddToData1);
		Btn_AddToData1.setBounds(350, 310, 150, 40);

		jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
		jPanel7.setLayout(null);

		Txt_NumClt1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_NumClt1ActionPerformed(evt);
			}
		});
		jPanel7.add(Txt_NumClt1);
		Txt_NumClt1.setBounds(120, 10, 130, 30);

		jLabel26.setText("Familly Name :");
		jPanel7.add(jLabel26);
		jLabel26.setBounds(10, 60, 85, 23);

		Txt_NomClt1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_NomClt1ActionPerformed(evt);
			}
		});
		jPanel7.add(Txt_NomClt1);
		Txt_NomClt1.setBounds(120, 50, 130, 30);

		jLabel27.setText("Given Name :");
		jPanel7.add(jLabel27);
		jLabel27.setBounds(10, 100, 85, 23);
		jPanel7.add(Txt_PreClt1);
		Txt_PreClt1.setBounds(120, 90, 130, 30);

		jLabel28.setText("Telephon :    (+212)");
		jPanel7.add(jLabel28);
		jLabel28.setBounds(10, 140, 110, 23);

		Txt_TeleClt1.setText("6");
		Txt_TeleClt1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_TeleClt1ActionPerformed(evt);
			}
		});
		jPanel7.add(Txt_TeleClt1);
		Txt_TeleClt1.setBounds(120, 130, 130, 30);

		jLabel29.setText("Num Client :");
		jPanel7.add(jLabel29);
		jLabel29.setBounds(10, 20, 85, 23);

		jPanel_Edit.add(jPanel7);
		jPanel7.setBounds(10, 10, 260, 170);

		getContentPane().add(jPanel_Edit);
		jPanel_Edit.setBounds(250, 180, 525, 360);

		jPanel_Search.setLayout(null);

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherhce",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
		jPanel5.setLayout(null);

		Combo_Search.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "N_Clt", "N_Immat", "Nom_Clt", "Prenom_Clt", "Tele", "N_RV", "Date_In", "Heur_In",
						"Date_Out", "Heur_Out", "Reparation", "Marque", "Model", "Num_Chas" }));
		Combo_Search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Combo_SearchActionPerformed(evt);
			}
		});
		jPanel5.add(Combo_Search);
		Combo_Search.setBounds(20, 20, 120, 30);
		jPanel5.add(Txt_Search);
		Txt_Search.setBounds(150, 20, 220, 30);

		jButton_Find.setText("Find");
		jButton_Find.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_FindActionPerformed(evt);
			}
		});
		jPanel5.add(jButton_Find);
		jButton_Find.setBounds(380, 20, 120, 30);

		jPanel_Search.add(jPanel5);
		jPanel5.setBounds(10, 20, 510, 60);

		tble1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] {
								{ null, null, null, null, null, null, null, null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null, null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null, null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null, null, null, null, null, null, null,
										null } },
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8",
						"Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14" }));
		tble1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		tble1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tble1MouseClicked(evt);
			}
		});
		jScrollPane3.setViewportView(tble1);

		jPanel_Search.add(jScrollPane3);
		jScrollPane3.setBounds(10, 90, 510, 220);

		jButton_FindDel.setText("Delete");
		jButton_FindDel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_FindDelActionPerformed(evt);
			}
		});
		jPanel_Search.add(jButton_FindDel);
		jButton_FindDel.setBounds(290, 320, 110, 30);

		jButton_FindEdit.setText("Edit");
		jButton_FindEdit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_FindEditActionPerformed(evt);
			}
		});
		jPanel_Search.add(jButton_FindEdit);
		jButton_FindEdit.setBounds(410, 320, 110, 30);

		getContentPane().add(jPanel_Search);
		jPanel_Search.setBounds(250, 180, 525, 360);

		jPanel_Delete.setLayout(null);

		tble.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] {
								{ null, null, null, null, null, null, null, null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null, null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null, null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null, null, null, null, null, null, null,
										null } },
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8",
						"Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14" }));
		tble.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		tble.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tbleMouseClicked(evt);
			}
		});
		jScrollPane2.setViewportView(tble);

		jPanel_Delete.add(jScrollPane2);
		jScrollPane2.setBounds(10, 10, 510, 300);

		jButton_Delete.setText("Delete Client");
		jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_DeleteActionPerformed(evt);
			}
		});
		jPanel_Delete.add(jButton_Delete);
		jButton_Delete.setBounds(390, 320, 130, 30);

		getContentPane().add(jPanel_Delete);
		jPanel_Delete.setBounds(250, 180, 525, 360);

		jPanel_Add.setPreferredSize(new java.awt.Dimension(1500, 1500));
		jPanel_Add.setLayout(null);

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Réparation",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
		jPanel3.setLayout(null);

		Txt_NRDV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_NRDVActionPerformed(evt);
			}
		});
		jPanel3.add(Txt_NRDV);
		Txt_NRDV.setBounds(100, 20, 130, 30);

		jLabel10.setText("Num_RDV");
		jPanel3.add(jLabel10);
		jLabel10.setBounds(30, 30, 85, 23);

		jLabel11.setText("Date_In");
		jPanel3.add(jLabel11);
		jLabel11.setBounds(30, 70, 85, 23);

		jLabel13.setText("Reparation");
		jPanel3.add(jLabel13);
		jLabel13.setBounds(270, 30, 85, 23);

		jLabel12.setText("Date_Out");
		jPanel3.add(jLabel12);
		jLabel12.setBounds(270, 70, 85, 23);
		jPanel3.add(DateC_Out);
		DateC_Out.setBounds(350, 60, 130, 30);
		jPanel3.add(DateC_In);
		DateC_In.setBounds(100, 60, 130, 30);

		Combo_Rep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rep 1", "Rep 2", "Rep 3", "Rep 4" }));
		jPanel3.add(Combo_Rep);
		Combo_Rep.setBounds(350, 20, 130, 30);

		jPanel_Add.add(jPanel3);
		jPanel3.setBounds(10, 200, 510, 100);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Voiture",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
		jPanel1.setLayout(null);

		jLabel6.setText("Immatrcule");
		jPanel1.add(jLabel6);
		jLabel6.setBounds(10, 20, 85, 23);

		jLabel7.setText("Marque");
		jPanel1.add(jLabel7);
		jLabel7.setBounds(10, 60, 85, 23);

		jLabel8.setText("Model");
		jPanel1.add(jLabel8);
		jLabel8.setBounds(10, 100, 85, 23);

		jLabel9.setText("Num_Chas");
		jPanel1.add(jLabel9);
		jLabel9.setBounds(10, 140, 85, 23);
		jPanel1.add(Txt_NChas);
		Txt_NChas.setBounds(90, 130, 130, 30);
		jPanel1.add(Txt_Model);
		Txt_Model.setBounds(90, 90, 130, 30);
		jPanel1.add(Txt_Marque);
		Txt_Marque.setBounds(90, 50, 130, 30);

		Txt_Immat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_ImmatActionPerformed(evt);
			}
		});
		jPanel1.add(Txt_Immat);
		Txt_Immat.setBounds(90, 10, 130, 30);

		jPanel_Add.add(jPanel1);
		jPanel1.setBounds(280, 10, 240, 170);

		Btn_AddToData.setText("Add To database");
		Btn_AddToData.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Btn_AddToDataActionPerformed(evt);
			}
		});
		jPanel_Add.add(Btn_AddToData);
		Btn_AddToData.setBounds(350, 310, 150, 40);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
		jPanel2.setLayout(null);

		Txt_NumClt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_NumCltActionPerformed(evt);
			}
		});
		jPanel2.add(Txt_NumClt);
		Txt_NumClt.setBounds(120, 10, 130, 30);

		jLabel14.setText("Familly Name :");
		jPanel2.add(jLabel14);
		jLabel14.setBounds(10, 60, 85, 23);

		Txt_NomClt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_NomCltActionPerformed(evt);
			}
		});
		jPanel2.add(Txt_NomClt);
		Txt_NomClt.setBounds(120, 50, 130, 30);

		jLabel15.setText("Given Name :");
		jPanel2.add(jLabel15);
		jLabel15.setBounds(10, 100, 85, 23);
		jPanel2.add(Txt_PreClt);
		Txt_PreClt.setBounds(120, 90, 130, 30);

		jLabel16.setText("Telephon :    (+212)");
		jPanel2.add(jLabel16);
		jLabel16.setBounds(10, 140, 110, 23);

		Txt_TeleClt.setText("6");
		Txt_TeleClt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_TeleCltActionPerformed(evt);
			}
		});
		jPanel2.add(Txt_TeleClt);
		Txt_TeleClt.setBounds(120, 130, 130, 30);

		jLabel17.setText("Num Client :");
		jPanel2.add(jLabel17);
		jLabel17.setBounds(10, 20, 85, 23);

		jPanel_Add.add(jPanel2);
		jPanel2.setBounds(10, 10, 260, 170);

		getContentPane().add(jPanel_Add);
		jPanel_Add.setBounds(250, 180, 525, 360);

		jLabel1.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/appstage/Files/Image(s)/BackGround copy.jpg"))); // NOI18N
		jLabel1.setPreferredSize(new java.awt.Dimension(810, 610));
		getContentPane().add(jLabel1);
		jLabel1.setBounds(0, -10, 810, 610);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void Txt_ImmatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_ImmatActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_ImmatActionPerformed

	private void Txt_NRDVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_NRDVActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_NRDVActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:*
		jPanel_Add.setVisible(true);
		jPanel_Delete.setVisible(false);
		jPanel_Search.setVisible(false);
		jPanel_Edit.setVisible(false);

	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		/*
		 * Select_Edit E = new Select_Edit(); this.setVisible(false);
		 * E.setVisible(true);
		 */

		if (JOptionPane.showConfirmDialog(null, "Trouvez le Client que vous voulez modifier ?", "Edit Client",
				JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
			jPanel_Add.setVisible(false);
			jPanel_Delete.setVisible(false);
			jPanel_Edit.setVisible(false);
			jPanel_Search.setVisible(true);
		} else {
			jPanel_Add.setVisible(true);
			jPanel_Delete.setVisible(false);
			jPanel_Search.setVisible(false);
			jPanel_Edit.setVisible(false);

		}

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		jPanel_Add.setVisible(false);
		jPanel_Delete.setVisible(true);
		jPanel_Search.setVisible(false);
		jPanel_Edit.setVisible(false);
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
		jPanel_Add.setVisible(false);
		jPanel_Delete.setVisible(false);
		jPanel_Search.setVisible(true);
		jPanel_Edit.setVisible(false);
	}// GEN-LAST:event_jButton5ActionPerformed

	private void Txt_NumCltActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_NumCltActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_NumCltActionPerformed

	private void Txt_NomCltActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_NomCltActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_NomCltActionPerformed

	private void Txt_TeleCltActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_TeleCltActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_TeleCltActionPerformed

	private void Btn_AddToDataActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Btn_AddToDataActionPerformed
		// TODO add your handling code here:
		String NumClient = Txt_NumClt.getText();
		String ImmatClient = Txt_Immat.getText();
		String NomClient = Txt_NomClt.getText();
		String PrenomClient = Txt_PreClt.getText();
		String TeleClient = Txt_TeleClt.getText();
		String NRDVClient = Txt_NRDV.getText();
		String DateInClient = DateC_In.getDate().toString(); // date_in
		// String NRDVClient=Txt_NRDV.getText(); time_in
		// String NRDVClient=Txt_NRDV.getText(); date_out
		// String NRDVClient=Txt_NRDV.getText(); time_out
		String ReparationClient = Combo_Rep.getSelectedItem().toString();
		String MarqueClient = Txt_Marque.getText();
		String ModelClient = Txt_Model.getText();
		String NChasClient = Txt_NChas.getText();

		String requete = "insert into Client(N_Clt,N_Immat,Nom_Clt,Prenom_Clt,Tele,N_RV,Date_In,Heur_In,Date_Out,Heur_Out,Reparation,Marque,Model,Num_Chas)VALUES('"
				+ NumClient + "','" + ImmatClient + "','" + NomClient + "','" + PrenomClient + "','" + TeleClient
				+ "','" + NRDVClient + "','" + TeleClient + "','" + TeleClient + "','" + TeleClient + "','" + TeleClient
				+ "','" + ReparationClient + "','" + MarqueClient + "','" + ModelClient + "','" + NChasClient + "')";

		// JOptionPane.showMessageDialog(null, DateInClient);

		try {
			// if(NumClient==null){
			stm.executeUpdate(requete);
			JOptionPane.showMessageDialog(null, "Client est bien ajouter");

			/*
			 * Txt_NumClt.setText(""); Txt_Immat.setText("");
			 * Txt_NomClt.setText(""); Txt_PreClt.setText("");
			 * Txt_TeleClt.setText(""); Txt_NRDV.setText(""); //Txt_NRDV
			 * //Txt_NRDV //Txt_NRDV //Txt_NRDV Combo_Rep.setSelectedItem(2);
			 * Txt_Marque.setText(""); Txt_Model.setText("");
			 * Txt_NChas.setText(""); //afficher();
			 */
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, /* ex.getMessage() */"Remplir les champs");
		}

	}// GEN-LAST:event_Btn_AddToDataActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton3ActionPerformed

	private void tbleMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbleMouseClicked
		try {
			int i = tble.getSelectedRow();
			deplace(i);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "erreur de deplacement " + e.getLocalizedMessage());
		}
	}// GEN-LAST:event_tbleMouseClicked

	private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_DeleteActionPerformed
		// TODO add your handling code here:
		// TODO add your handling code here:
		int Row = tble.getSelectedRow();
		String S = model.getValueAt(Row, 0).toString();
		// JOptionPane.showMessageDialog(null,tble.getComponentAt(Row, 1));
		// JOptionPane.showMessageDialog(null,Row);

		try {
			if (JOptionPane.showConfirmDialog(null, "attention vous avez supprimer un etudient,est ce que tu et sure?",
					"supprimer etudient", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
				if (Row != -1) {
					stm.executeUpdate("Delete From Client where N_Clt = " + S); // afficher();
				} else {
					JOptionPane.showMessageDialog(null, "Select a Client");
				}
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "erreur de supprimer \n" + e.getMessage());
		}
		Refresh();
	}// GEN-LAST:event_jButton_DeleteActionPerformed

	private void Combo_SearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Combo_SearchActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Combo_SearchActionPerformed

	private void jButton_FindActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_FindActionPerformed
		// TODO add your handling code here

		String S = Combo_Search.getSelectedItem().toString();
		// JOptionPane.showMessageDialog(null,S);

		try {
			model.setRowCount(0);// pour vider la list des etudient
			{
				S = "Select * From Client WHERE " + S + " = '" + Txt_Search.getText() + "'";
				Rs = stm.executeQuery(S);
			}
			while (Rs.next()) {
				Object[] Client = { Rs.getInt(1), Rs.getString(2), Rs.getString(3), Rs.getString(4), Rs.getInt(5),
						Rs.getInt(5), Rs.getInt(5), Rs.getInt(5), Rs.getInt(5), Rs.getInt(5), Rs.getInt(5),
						Rs.getInt(5), Rs.getInt(5), Rs.getInt(5) };
				model.addRow(Client);
			}
			if (model.getRowCount() == 0) {
				JOptionPane.showMessageDialog(null, "il y a aucun Client");
			} else {
				int i = 0;
				deplace(i);
			}

		} catch (Exception e) {
			System.err.println(e);
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
		// JOptionPane.showMessageDialog(null,S);
	}// GEN-LAST:event_jButton_FindActionPerformed

	private void tble1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tble1MouseClicked
		try {
			int i = tble1.getSelectedRow();
			deplace(i);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "erreur de deplacement " + e.getLocalizedMessage());
		}
	}// GEN-LAST:event_tble1MouseClicked

	private void jButton_FindDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_FindDelActionPerformed
		// TODO add your handling code here:
		int Row = tble1.getSelectedRow();
		String S = model.getValueAt(Row, 0).toString();
		// JOptionPane.showMessageDialog(null,tble.getComponentAt(Row, 1));
		// JOptionPane.showMessageDialog(null,Row);

		try {
			if (JOptionPane.showConfirmDialog(null, "attention vous avez supprimer un etudient,est ce que tu et sure?",
					"supprimer etudient", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
				if (Row != -1) {
					stm.executeUpdate("Delete From Client where N_Clt = " + S); // afficher();
				} else {
					JOptionPane.showMessageDialog(null, "Select a Client");
				}
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "erreur de supprimer \n" + e.getMessage());
		}
		Refresh();
	}// GEN-LAST:event_jButton_FindDelActionPerformed

	private void jButton_FindEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_FindEditActionPerformed
		jPanel_Add.setVisible(false);
		jPanel_Delete.setVisible(false);
		jPanel_Search.setVisible(false);
		jPanel_Edit.setVisible(true);
	}// GEN-LAST:event_jButton_FindEditActionPerformed

	private void Txt_NRDV1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_NRDV1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_NRDV1ActionPerformed

	private void Txt_Immat1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_Immat1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_Immat1ActionPerformed

	private void Btn_AddToData1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Btn_AddToData1ActionPerformed

	}// GEN-LAST:event_Btn_AddToData1ActionPerformed

	private void Txt_NumClt1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_NumClt1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_NumClt1ActionPerformed

	private void Txt_NomClt1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_NomClt1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_NomClt1ActionPerformed

	private void Txt_TeleClt1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_TeleClt1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_TeleClt1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Add().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Btn_AddToData;
	private javax.swing.JButton Btn_AddToData1;
	private javax.swing.JComboBox Combo_Rep;
	private javax.swing.JComboBox Combo_Rep1;
	private javax.swing.JComboBox Combo_Search;
	public com.toedter.calendar.JDateChooser DateC_In;
	public com.toedter.calendar.JDateChooser DateC_In1;
	public com.toedter.calendar.JDateChooser DateC_Out;
	public com.toedter.calendar.JDateChooser DateC_Out1;
	private javax.swing.JTextField Txt_Immat;
	private javax.swing.JTextField Txt_Immat1;
	private javax.swing.JTextField Txt_Marque;
	private javax.swing.JTextField Txt_Marque1;
	private javax.swing.JTextField Txt_Model;
	private javax.swing.JTextField Txt_Model1;
	private javax.swing.JTextField Txt_NChas;
	private javax.swing.JTextField Txt_NChas1;
	public javax.swing.JTextField Txt_NRDV;
	public javax.swing.JTextField Txt_NRDV1;
	private javax.swing.JTextField Txt_NomClt;
	private javax.swing.JTextField Txt_NomClt1;
	private javax.swing.JTextField Txt_NumClt;
	private javax.swing.JTextField Txt_NumClt1;
	private javax.swing.JTextField Txt_PreClt;
	private javax.swing.JTextField Txt_PreClt1;
	private javax.swing.JTextField Txt_Search;
	private javax.swing.JTextField Txt_TeleClt;
	private javax.swing.JTextField Txt_TeleClt1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton_Delete;
	private javax.swing.JButton jButton_Find;
	private javax.swing.JButton jButton_FindDel;
	private javax.swing.JButton jButton_FindEdit;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel_Add;
	private javax.swing.JPanel jPanel_Delete;
	private javax.swing.JPanel jPanel_Edit;
	private javax.swing.JPanel jPanel_Search;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable tble;
	private javax.swing.JTable tble1;
	// End of variables declaration//GEN-END:variables

	/**
	 * @return the Txt_NomClt
	 */
	public javax.swing.JTextField getTxt_NomClt() {
		return Txt_NomClt;
	}

	/**
	 * @return the Txt_NumClt
	 */
	public javax.swing.JTextField getTxt_NumClt() {
		return Txt_NumClt;
	}

	/**
	 * @return the Txt_PreClt
	 */
	public javax.swing.JTextField getTxt_PreClt() {
		return Txt_PreClt;
	}

	/**
	 * @return the Txt_TeleClt
	 */
	public javax.swing.JTextField getTxt_TeleClt() {
		return Txt_TeleClt;
	}

	/**
	 * @return the Txt_Immat
	 */
	public javax.swing.JTextField getTxt_Immat() {
		return Txt_Immat;
	}

	/**
	 * @return the DateC_In
	 */
	public com.toedter.calendar.JDateChooser getDateC_In() {
		return DateC_In;
	}

	/**
	 * @return the DateC_Out
	 */
	public com.toedter.calendar.JDateChooser getDateC_Out() {
		return DateC_Out;
	}

	/**
	 * @return the Combo_Rep
	 */
	public javax.swing.JComboBox getCombo_Rep() {
		return Combo_Rep;
	}

	/**
	 * @return the Txt_Marque
	 */
	public javax.swing.JTextField getTxt_Marque() {
		return Txt_Marque;
	}

	/**
	 * @return the Txt_Model
	 */
	public javax.swing.JTextField getTxt_Model() {
		return Txt_Model;
	}

	/**
	 * @return the Txt_NChas
	 */
	public javax.swing.JTextField getTxt_NChas() {
		return Txt_NChas;
	}
}
